from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class AlgorithmProblem(models.Model):
    # Difficulty Choices
    DIFFICULTY_CHOICES = [
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ]

    # Core Metadata
    problem_id = models.IntegerField(unique=True, help_text="The exact ID from the JSON batch.")
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    difficulty_level = models.CharField(max_length=20, choices=DIFFICULTY_CHOICES)
    elo_requirement = models.IntegerField(help_text="e.g., 800, 1200, 1600")
    
    # Tags stored as a JSON array of strings: e.g., ["Arrays", "Two Pointers"]
    topic_tags = models.JSONField(default=list, blank=True)

    # Problem Content
    problem_description = models.TextField()
    starter_code = models.TextField(blank=True, default="def solution():\n    pass")
    reference_solution = models.TextField()
    
    # Grading & Support
    key_concepts_to_check = models.TextField(help_text="Instructions for the Cohere LLM Judge.")
    progressive_hints = models.JSONField(default=list, blank=True, help_text="List of hint strings.")

    # --- NEW: AI Generation Tracking ---
    is_ai_generated = models.BooleanField(default=False, help_text="True if generated by command-a-03-2025 API.")
    generated_by = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,  # Deletes AI problems if the user deletes their account to save DB space
        null=True, 
        blank=True, 
        related_name='generated_problems'
    )

    # Timestamps for your database records
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['problem_id']
        verbose_name = "Algorithm Problem"
        verbose_name_plural = "Algorithm Problems"

    def __str__(self):
        prefix = "[AI] " if self.is_ai_generated else ""
        return f"{prefix}[{self.problem_id}] {self.title} - {self.elo_requirement} Elo"

class ProblemSubmission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='submissions')
    problem = models.ForeignKey(AlgorithmProblem, on_delete=models.CASCADE, related_name='submissions')
    
    submitted_code = models.TextField()
    passed = models.BooleanField(default=False, help_text="True if Cohere marked it as perfectly correct.")
    llm_feedback = models.TextField(help_text="The advice generated by the AI judge.")
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        status = "PASSED" if self.passed else "FAILED"
        return f"[{status}] {self.user.username} - {self.problem.title}"

from django.db import models
from django.contrib.auth.models import User

# (Make sure you have your AlgorithmProblem model defined above this or imported)

class Duel(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending - Waiting for Opponent'),
        ('active', 'Active - Timers are ticking'),
        ('grading', 'Grading - Sent to AI Judge'),
        ('completed', 'Completed - Winner Declared'),
    ]

    # The Fighters
    challenger = models.ForeignKey(User, on_delete=models.CASCADE, related_name='duels_initiated')
    opponent = models.ForeignKey(User, on_delete=models.CASCADE, related_name='duels_received')
    
    # The Arena (The generated AI problem)
    problem = models.ForeignKey('AlgorithmProblem', on_delete=models.CASCADE, related_name='duels')

    # The Independent Timers (For our Lazy Evaluation)
    challenger_start_time = models.DateTimeField(null=True, blank=True)
    opponent_start_time = models.DateTimeField(null=True, blank=True)

    # The Submitted Code (Saved so the AI can compare them)
    challenger_code = models.TextField(blank=True, null=True)
    opponent_code = models.TextField(blank=True, null=True)

    # Game State
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    
    # The Victor
    winner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='duels_won')

    # Standard Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "AI Arena Duel"
        verbose_name_plural = "AI Arena Duels"

    def __str__(self):
        return f"Duel: {self.challenger.username} vs {self.opponent.username} [{self.get_status_display()}]"        


class TechDomain(models.Model):
    # Name used in the backend (e.g., 'oop', 'dsa', 'ccna')
    name = models.CharField(max_length=50, unique=True)
    
    # Human-readable name used for UI display (e.g., 'Object Oriented Programming', 'CCNA Networking')
    display_name = models.CharField(max_length=100)
    
    # TRACKING RELATIONSHIP: Who created/seeded this topic into the ecosystem
    created_by = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        related_name='created_domains'
    )
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.display_name


class CertificationQuizAttempt(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending Review'),
        ('verified', 'Verified & Issued'),
        ('rejected', 'Rejected by Staff'),
    )

    student = models.ForeignKey(
        User, 
        on_delete=models.CASCADE, 
        related_name='certification_attempts'
    )
    
    domain = models.ForeignKey(
        TechDomain, 
        on_delete=models.CASCADE, 
        related_name='attempts'
    )
    
    # THE AI DATA STREAMS: Storing raw dictionaries/lists for maximum extensibility
    # Stores the 20 MCQs with questions, choices, and answer key from Cohere
    generated_quiz_data = models.JSONField(
        default=dict, 
        help_text="Stores the AI-generated questions, multiple options, and correct answers."
    )
    
    # Stores the options selected by the student during the test
    user_responses = models.JSONField(
        default=dict, 
        blank=True, 
        help_text="Stores the student's selected choices for tracking."
    )
    
    # Computed immediately by Python upon submission
    score_percentage = models.FloatField(default=0.0)
    
    status = models.CharField(
        max_length=20, 
        choices=STATUS_CHOICES, 
        default='pending'
    )
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # Tracks which staff member manually reviews and drops the final seal of approval
    reviewed_by = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        blank=True, 
        null=True, 
        related_name='reviewed_certifications'
    )

    class Meta:
        # THE CORE SECURITY GATE: Prevents a student from taking multiple quizes for the same topic!
        unique_together = ('student', 'domain')
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.student.username} - {self.domain.display_name} ({self.get_status_display()})"    
    
    
    
    
    
    
    
    
    
    
    
    
    
    