# Generated by Django 6.0.3 on 2026-05-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_level',
            field=models.CharField(default='beginner', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='target_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
