# Generated by Django 6.0.3 on 2026-05-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0002_profile_interests_profile_role_profile_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elo_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
