# Generated by Django 6.0.3 on 2026-05-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(help_text='The exact ID from the JSON batch.', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('elo_requirement', models.IntegerField(help_text='e.g., 800, 1200, 1600')),
                ('topic_tags', models.JSONField(blank=True, default=list)),
                ('problem_description', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='def solution():\n    pass')),
                ('reference_solution', models.TextField()),
                ('key_concepts_to_check', models.TextField(help_text='Instructions for the Cohere LLM Judge.')),
                ('progressive_hints', models.JSONField(blank=True, default=list, help_text='List of hint strings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Algorithm Problem',
                'verbose_name_plural': 'Algorithm Problems',
                'ordering': ['problem_id'],
            },
        ),
    ]
