# Generated by Django 6.0.3 on 2026-05-16 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeApp', '0002_problemsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmproblem',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='algorithmproblem',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='True if generated by command-a-03-2025 API.'),
        ),
    ]
