# Generated by Django 6.0.3 on 2026-05-18 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeApp', '0003_algorithmproblem_generated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger_start_time', models.DateTimeField(blank=True, null=True)),
                ('opponent_start_time', models.DateTimeField(blank=True, null=True)),
                ('challenger_code', models.TextField(blank=True, null=True)),
                ('opponent_code', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Waiting for Opponent'), ('active', 'Active - Timers are ticking'), ('grading', 'Grading - Sent to AI Judge'), ('completed', 'Completed - Winner Declared')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_initiated', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_received', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='PracticeApp.algorithmproblem')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duels_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Arena Duel',
                'verbose_name_plural': 'AI Arena Duels',
                'ordering': ['-created_at'],
            },
        ),
    ]
