# Generated by Django 6.0.3 on 2026-05-26 10:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('internship', 'Internship')], default='full_time', max_length=50)),
                ('location', models.CharField(blank=True, help_text='e.g., Lahore, PK or Remote', max_length=255, null=True)),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $50k - $70k or Rs. 100k', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(help_text='Upload your CV. Only PDF, DOC, and DOCX files are allowed.', upload_to='cv_uploads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('cover_letter', models.TextField(blank=True, help_text='Introduce yourself and explain why you are a great fit for this specific role.', null=True)),
                ('relevant_project_url', models.URLField(blank=True, help_text='Link to a specific GitHub repo or project relevant to this job.', null=True)),
                ('availability', models.CharField(choices=[('immediate', 'Immediately'), ('two_weeks', 'In 2 Weeks'), ('one_month', 'In 1 Month'), ('student', 'Currently Enrolled (Part-time only)')], default='immediate', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='JobsApp.jobposting')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('applicant', 'job')},
            },
        ),
    ]
