# Generated by Django 6.0.3 on 2026-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(blank=True, default='unknown', max_length=255, null=True),
        ),
    ]
